# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ebdde11194168ad2984831ad1911d6c74b5427a06f3efde5ac4c3a6843ff39333f7b895bc42fb09ad5a96af8c68390af81017a2ad4d6ddc6c6b023e3efb08a57

test:
  secret_key_base: 6ec3ba1c176cba7593eeebc675b8fea88741d05f1f490ad2fdf13e67d2dcf245211ca0338938181603e13dddad003fe7aee558989530771901fca1baa7b48ab9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
